config/routes.rb
Wwcode::Application.routes.draw do

  root 'about#index'

  resources :about

  resources :admins
  resources :blogs
  resources :audience_emails
  resources :sessions, only: [:new,:create,:destroy]

  match '/admin_signup', to: 'admins#new', via: :get
  match '/admin_signin', to: 'sessions#new', via: :get
  match '/admin_signout', to: 'sessions#destroy', via: :delete
  match '/community', to: 'community#index', via: :get

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true

  def Admin.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Admin.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = Admin.encrypt(Admin.new_remember_token)
    end
end

app/models/audience_email.rb
class AudienceEmail < ActiveRecord::Base
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_action :signed_in_admin, only: [:edit, :update]

  def index
     @about = About.first
     @email = AudienceEmail.new
  end

  def edit
    @about = About.first
  end

  def update
    @about = About.first

    if @about.update_attributes(about_params)
      redirect_to current_admin
    else
      render 'edit'
    end
  end


  private
    def about_params
      params.require(:about).permit(:mission,:studynights,:hackevents,:techtalks)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :signed_in_admin, only: [:show]
  before_action :correct_admin, only: [:show]

  def new
    @admin = Admin.new
  end

  def show

  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      render 'review'
    else
      render 'new'
    end
  end

  private
    def admin_params
      params.require(:admin).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/audience_emails_controller.rb
class AudienceEmailsController < ApplicationController
  def create
    @email = AudienceEmail.new(audience_email_params)
    @email.save
    redirect_to root_url
  end

  private
    def audience_email_params
      params.require(:audience_email).permit(:email)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :signed_in_admin, only: [:new,:edit,:update]

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to current_admin
    else
      render 'new'
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(blog_params)
      redirect_to blogs_url
    else
      render 'edit'
    end
  end

  def index
    @blogs_all = Blog.all
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_url
  end


  private
    def blog_params
      u = params.require(:blog).permit(:title,:para1,:para2,:para3,:author)
      u["admin_id"] = current_admin.id 
      u
    end

end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def edit
  end

  def update
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.where(email: params[:session][:email]).first
    if admin && admin.authenticate(params[:session][:password])
      sign_in admin
      redirect_back_or admin
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def location_name
    if @location
      @location.name
    else
      ""
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(admin)
    remember_token = Admin.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    admin.update_attribute(:remember_token,Admin.encrypt(remember_token))
    self.current_admin = admin
  end

  def current_admin=(admin)
    @current_admin = admin
  end

  def current_admin
    remember_token = Admin.encrypt(cookies[:remember_token])
    @current_admin ||= Admin.where(remember_token: remember_token).first
  end

  def signed_in?
    !current_admin.nil?
  end

  def sign_out
    current_admin.update_attribute(:remember_token, Admin.encrypt(Admin.new_remember_token))
    cookies.delete(:remember_token)
    self.current_admin = nil
  end

  def current_admin?(admin)
    admin == current_admin
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def signed_in_admin
    unless signed_in?
      store_location
      redirect_to admin_signin_url, notice: "please sign in"
    end
  end

  def correct_admin
    @admin = Admin.find(params[:id])
    redirect_to(root_url) unless (current_admin?(@admin) && @admin.trust)
  end
end

app/views/about/_newsletter.html.erb
<h2 class="double-inner">NewsLetter Signup</h2>
<%= form_for @email, :html => {:class => 'lastUnit news-letter'} do |f| %>
<%= f.text_field :email %>
<%= f.submit 'Register' %>
<% end %>

app/views/about/edit.html.erb
<h2 class="double-inner"> Be Careful in editing the content here it is going to change the Landing PAGE </h2>

<div class="inner">
<%= form_for(@about) do |f| %>
<div class="row">
  <%= f.label :mission %>
</div>

<div class="row bottom-inner">
  <%= f.text_area :mission, size: "100x5" %>
</div>

<div class="row">
  <%= f.label :study %>
</div>

<div class="row bottom-inner">
  <%= f.text_area :studynights, size: "100x5" %>
</div>

<div class="row">
<%= f.label :hack %>
</div>

<div class="row bottom-inner">
<%= f.text_area :hackevents, size: "100x5" %>
</div>

<div class="row">
<%= f.label :tech %>
</div>

<div class="row bottom-inner">
<%= f.text_area :techtalks, size: "100x5" %>
</div>

<%= f.submit %>

<% end %>
</div>

app/views/about/index.html.erb
<div class="row main-image-container">
  <%= image_tag("main-image.jpg") %>
</div>

<div class="row some-height">
</div>

<div class="row">
  <div class="unit col1of2 borderright double-inner">
    <h2>Who We are?</h2>
    <p class="inner"><%= @about.mission %></p>
  </div>
  <div class"lastUnit news-letter">
    <%= render 'newsletter' %>
  </div>
</div>

<div class="row">
  <h2 class="double-inner">How we do?</h2>

  <div class="unit col1of3 borderright double-inner">
    <h4>Study Nights</h4>
    <p class="inner"><%= @about.studynights %></p>
  </div>
  <div class="unit col1of3 borderright double-inner">
    <h4>Hack Events</h4>
    <p class="inner"><%= @about.hackevents %></p>
  </div>
  <div class="unit lastUnit double-inner">
    <h4>Tech Talks</h4>
    <p class="inner"><%= @about.techtalks %></p>
  </div>
</div>

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
<div class="row">
  <%= f.label :name %>
</div>

<div class='row'>
  <%= f.text_field :name %>
</div>

<div class="row">
  <%= f.label :email %>
</div>

<div class="row">
  <%= f.text_field :email %>
</div>

<div class="row">
  <%= f.label :password %>
</div>

<div class="row">
  <%= f.password_field :password %>
</div>

<div class="row">
  <%= f.label :password_confirmation %>
</div>
<div class="row">
  <%= f.password_field :password_confirmation %>
</div>

<div class="row">
  <%= f.submit %>
</div>

<% end %>

app/views/admins/new.html.erb
<div class="row">
  <div class="unit col1of3 some-height"></div>
  <div class="unit col1of3">
  <div class="row vertical-double-inner">
    <h1>Admin Sign Up</h1>
  </div>
  <div class="row">
    <%= render 'shared/error_messages' %>
  </div>
  <%= render 'form' %>
</div>
<div class="unit col1of3"></div>
</div>

app/views/admins/review.html.erb
<div> Your account is under review please email sowju19@gmail.com </div>

app/views/admins/show.html.erb
<div class="row double-inner f-right"> 
  <%= link_to 'Sign_Out', {controller: 'sessions', id: current_admin.id, action: 'destroy'}, method: :delete %>
</div>

<div class="admin-wrapper">
  <div class="row double-inner">
    <%= link_to 'Create Blog', new_blog_path %>
  </div>
  <div class="row double-inner">
    <%= link_to 'Edit About', {controller: 'about', action: 'edit'} %>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
<div class="row">
  <%= f.label  :title %>
</div>
<div class="row">
  <%= f.text_field :title %>
</div>

<div class="row">
  <%= f.label :paragraph1 %>
</div>

<div class="row bottom-inner">
  <%= f.text_area :para1, size: "100x10" %>
</div>

<div class="row">
  <%= f.label :paragraph2 %>
</div>
<div class="row bottom-inner">
  <%= f.text_area :para2, size: "100x10" %>
</div>

<div class="row">
  <%= f.label :paragraph3 %>
</div>
<div class="row bottom-inner">
  <%= f.text_area :para3, size: "100x10" %>
</div>

<div class="row">
  <%= f.label :author %>
</div>
<div class="row bottom-inner">
  <%= f.text_field :author %>
</div>

  <div class="row">
    <%= f.submit %>
  </div>

  <% end %>

app/views/blogs/edit.html.erb
<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="unit col1of4">
  <div class="row recent-posts inner">Recent Posts</div>
  <% @blogs_all.each do |blog| %>
  <div class="row nav-blog horizontal-double-inner">
    <%= link_to blog.title, blog_path(blog) %>
  </div>
  <% end %>
</div>

<div class="unit col2of3">
  <% @blogs_all.each do |blog| %>
  <div class="each-blog double-inner">
    <div class="blog-title"><%=blog.title%></div>
    <p><%=blog.para1%>...</p>
    <div class="row">
      <% if signed_in? %>
        <%= link_to 'edit', edit_blog_path(blog)%>
        <%= link_to 'Delete Blog', {controller: 'blogs', action: 'destroy', id: blog.id}, method: :delete %>
      <% end %>
      <div class="blog-author">---<%=blog.author%></div>
    </div>
  </div>
<% end %>
</div>

app/views/blogs/new.html.erb
<div class="blog-wrapper">

<%= render 'form' %> 
</div>

app/views/blogs/show.html.erb
  <div class="double-inner">
    <div class="blog-title"><%=@blog.title%></div>

    <p><%= @blog.para1 %></p>

    <p><%= @blog.para2 %></p>

    <p><%= @blog.para3 %></p>

    <div class="row">
      <% if signed_in? %>
      <%= link_to 'edit', edit_blog_path(@blog)%>
      <%= link_to 'Delete Blog', {controller: 'blogs', action: 'destroy', id: @blog.id}, method: :delete %>
      <% end %>
      <div class="blog-author">---<%= @blog.author%></div>
    </div>
  </div>

app/views/community/index.html.erb
<div class="row inner">
  <h2>We have chapters in 10 countries</h2>
</div>

app/views/layouts/_header.html.erb
  <div class="row header-container">
    <div class="unit col1of3 horizontal-double-inner vertical-inner">
      <h1>WOMEN WHO CODE</h1>
    </div>
    <div class="unit col1of3 f-right double-inner">
      <a href="/">About</a>
      <a href="/blogs">Blogs</a>
      <a href="/community">Community</a>
      <a href="#">Donate</a>
    </div>
  </div>
  

app/views/layouts/_login.html.erb
<div class="row admin-background">
  <div class="unit col1of2">
    <%= link_to "Current Admin", {controller: 'admins', action: 'show', id: current_admin.id} %>
  </div>
  <div class="row col1of2">
    <%= link_to "Logout", {controller: 'sessions', action: 'destroy', id: current_admin.id}, method: :delete %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>wwc</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% if signed_in? %>
  <%= render 'layouts/login' %>
  <% end %>
  <div class="main-container">
  <div class="row main-content">
  <%= yield %>
</div>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<div class="row">
  <% if @admin.errors.any? %>
    <div class="alert">
      This form contains <%= pluralize(@admin.errors.count, "error") %>
    </div>

    <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li> *<%= msg %> </li>
      <% end %>
    </ul>
  <% end %>
</div>